ProjektGruppF/ProjektGruppF/Models/Extended/freelancer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ProjektGruppF.Models
{

    [MetadataType(typeof(freelancerMetadatad))]
    public partial class freelancer
    {
        public string confirmpassword { get; set; }


    }

    public class freelancerMetadatad
    {
        [Required(ErrorMessage = " oops, seems like you forgott to type your name. ")]
        public string firstname { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your lastname. ")]


        public string lastname { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your adress. ")]

        public string adress { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your email. ")]

        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your phone number.")]
        public Nullable<int> phonenumber { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = " oops, seems like you forgott to type your password.")]
        public string password { get; set; }

        [DataType(DataType.Password)]

        [Compare("password", ErrorMessage ="Passwords are not matching.")]
        public string confirmpassword { get; set; }
    }
}

ProjektGruppF/ProjektGruppF/Models/cv.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class cv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cv()
        {
            this.freelancer = new HashSet<freelancer>();
            this.education_cv = new HashSet<education_cv>();
            this.language_cv = new HashSet<language_cv>();
            this.work_experience = new HashSet<work_experience>();
            this.expertise_cv = new HashSet<expertise_cv>();
            this.skill_cv = new HashSet<skill_cv>();
            this.main_abilities_cv = new HashSet<main_abilities_cv>();
        }
    
        public int cv_id { get; set; }
        [DisplayName ("Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime birthday { get; set; }
        [DisplayName("Nationality")]

        public string nationality { get; set; }
        [DisplayName("Drivers License")]

        public string drivers_license { get; set; }

        public Nullable<System.DateTime> registration_date { get; set; }
        [DisplayName("Profile")]

        public string profil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<freelancer> freelancer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<education_cv> education_cv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<language_cv> language_cv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_experience> work_experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expertise_cv> expertise_cv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill_cv> skill_cv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<main_abilities_cv> main_abilities_cv { get; set; }

        //public List<language> LanguageList { get; set; }
        //public language language_id { get; set; }
        //public language name { get; set; }
        //public string Language { get; set; }
        //public string name { get; set; }
        public int language_id { get; set; }

        //public int? language_id { get; internal set; }
    }
}

ProjektGruppF/ProjektGruppF/Controllers/CV_Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektGruppF.Models;

namespace ProjektGruppF.Controllers
{
    public class CV_Controller : Controller
    {
        private ProjektGruppFEntities1 db = new ProjektGruppFEntities1();

        // GET: CV_
        //public ActionResult Index()
        //{
        //    return View(db.cv.ToList());
        //}

        public ActionResult Index()
        {

            return View(db.cv.ToList());
        }

        public ActionResult Index()
        {
            CvFreelancerOperations cvfO = new CvFreelancerOperations();
            
            return View(cvfO.FreelancercardVMList());
        }

        // GET: CV_/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cv cv = db.cv.Find(id);
            if (cv == null)
            {
                return HttpNotFound();
            }
            return View(cv);
        }

        // GET: CV_/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CV_/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cv_id,birthday,nationality,drivers_license,registration_date,profil")] cv cv)

        {
            if (ModelState.IsValid)
            {
                db.cv.Add(cv);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cv);
        }

        // GET: CV_/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    cv cv = db.cv.Find(id);
        //    if (cv == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(cv);
        //}

        public ActionResult Edit(int? id)
        {
            if (id == null)
            { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            var languageViewModel = new language
            { Cv = db.cv.Include(i => i.Language).First(i => i.cv_id == id), };

            if (languageViewModel.Cv == null)
                return HttpNotFound();


            var languagesList = db.language.ToList();
            languageViewModel.AllLanguages = languagesList.Select(o => new SelectListItem { Text = o.name, Value = o.language_id.ToString() });

            ViewBag.EmployerID = new SelectList(db.freelancer, "Id", "Name", languageViewModel.Cv.freelancer_id);

            return View(languageViewModel);
        }


        // POST: CV_/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cv_id,birthday,nationality,drivers_license,registration_date,profil")] cv cv)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cv).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cv);
        }

        // GET: CV_/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cv cv = db.cv.Find(id);
            if (cv == null)
            {
                return HttpNotFound();
            }
            return View(cv);
        }

        // POST: CV_/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cv cv = db.cv.Find(id);
            db.cv.Remove(cv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjektGruppF/ProjektGruppF/Controllers/freelancersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektGruppF.Models;
using ProjektGruppF.ViewModels;

namespace ProjektGruppF.Controllers
{
    public class freelancersController : Controller

        //TESTLinda
    {
        FreelancerCardOperations fc = new FreelancerCardOperations();

        private ProjektGruppFEntities1 db = new ProjektGruppFEntities1();

            savedFreelancersOperations sOP = new savedFreelancersOperations();
        SavedFreelancersVM sf = new SavedFreelancersVM();
        // GET: freelancers
        public ActionResult Index()
        {
            var freelancer = db.freelancer.Include(f => f.cv);
            return View(freelancer);
        }
        public ActionResult skills_Expertiser()
        {
            List<string> skills = new List<string>();
            skills.Add("All Skills");
            skills.Add("Programming");
            skills.Add("Web developing");
            skills.Add("Databases");
            skills.Add("Mobile applications developing");
            SelectList skillsList = new SelectList(skills);
            ViewData["skillsList"] = skillsList;
            return View(sf);

        }
        [HttpPost]
        public ActionResult skills_Expertiser([Bind(Include = "expertise_id,cv_id")] expertise_cv expertise)
        {
            if (ModelState.IsValid)
            {   
                db.expertise_cv.Add(expertise);
                db.SaveChanges();
                return RedirectToAction("EditMainAbilities", "CVversion3");
            }
            return View();

        }

        // GET: freelancers/Details/5
        public ActionResult Start(int? id=9)
        {
            

            //ViewBag.skill = new SelectList(db.skill, "skill_id", "name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            freelancer freelancer = db.freelancer.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            return View(freelancer);
        }
        public ActionResult CV(int freelancer_id=9, int cv_id=7)
        {
            if (freelancer_id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FreelancerCardOperations flc = new FreelancerCardOperations();

            if (cv_id == 0)
            {
                return HttpNotFound();
            }
            return View(flc.ViewFreelancer(freelancer_id, cv_id));
        }

        // GET: freelancers/Create
        public ActionResult Create()
        {
           // ViewBag.cv_id = new SelectList(db.cv, "cv_id", "nationality");
            return View();
        }

        // POST: freelancers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "freelancer_id,firstname,lastname,adress,phonenumber,email,cv_id")] freelancer freelancer)
        {
            if (ModelState.IsValid)
            {
                
                db.freelancer.Add(freelancer);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            //ViewBag.cv_id = new SelectList(db.cv, "cv_id", "nationality", freelancer.cv_id);
            return View(freelancer);
        }

        // GET: freelancers/Edit/5
        public ActionResult Edit(int? id=9)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            freelancer freelancer = db.freelancer.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            ViewBag.cv_id = new SelectList(db.cv, "cv_id", "nationality", freelancer.cv_id);
            return View(freelancer);
        }

        // POST: freelancers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cv_id,freelancer_id,firstname,lastname,adress,phonenumber,email,PersonalLetter")] freelancer freelancer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(freelancer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Start");
            }
            ViewBag.cv_id = new SelectList(db.cv, "cv_id", "nationality", freelancer.cv_id);
            return View(freelancer);
        }

        // GET: freelancers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            freelancer freelancer = db.freelancer.Find(id);
            if (freelancer == null)
            {
                return HttpNotFound();
            }
            return View(freelancer);
        }

        // POST: freelancers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            freelancer freelancer = db.freelancer.Find(id);
            db.freelancer.Remove(freelancer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult GetExpertises(string skills)
        {
            List<string> expertises = new List<string>();
            List<string> s = new List<string>();
            s.Add(skills);
            fc.UppdateSkill_cv(12, s);
            switch (skills)
            {
                case "Programming":
                    expertises.Add("C#");
                    expertises.Add("Java");
                    expertises.Add("Python");
                    break;
                case "Web developing":
                    expertises.Add("HTML");
                    expertises.Add("CSS");
                    expertises.Add("Javascript");
                    expertises.Add("JQuery");
                    expertises.Add("PHP");
                    break;
                case "Databases":
                    expertises.Add("Postgres");
                    expertises.Add("Oracle");
                    expertises.Add("MySQL");
                    break;
                case "Mobile applications developing":
                    expertises.Add("Android");
                    expertises.Add("IOS");
                    break;
            }
            return Json(expertises);
        }
    }
}

ProjektGruppF/ProjektGruppF/Views/freelancers/CV.cshtml
@model ProjektGruppF.ViewModels.Freelancer

@{
    ViewBag.Title = "CV";
    Layout = "~/Views/Shared/_FreelancerLayout.cshtml";
}

<div class="col-md-9">
    <div class="card border-secondary mb-3">
        <div class=" card-header">
            <h5 style="text-align:center">Curriculum Vitae</h5>
        </div>
        <div class="card-body">
            <h5 class="card-title">@Model.Firstname @Model.Lastname</h5>
            <p class="card-text">
                @Model.CoverLetter
                <hr />
                Adress: @Model.Adress  <br>
                Phonenumber: @Model.Phonenumber  <br>
                Email: @Model.Email  <br>
                Birthday: @Model.Birthday  <br>
                Nationality: @Model.Nationality  <br>
                Drivers license: @Model.Drivers_license  <br><br>
                <hr>
                <h5 class="card-title" font-weight: bold;">Work experience</h5>
                @*@foreach (var item in Model.Work_Experience_List)
        {
            if (item.cv_id == 7)
            {
                <p>Employer:@item.employer_name<p/>


             }
               }*@

                @foreach (var item in Model.Work_Experience_List)
                {
                    if (item.cv_id == 7)
                    {
                        <p>Employer: @item.employer_name</p>
                        <p>Job title: @item.job_title</p>
                        <p>Role: @item.role</p>
                        <p>Start date: @item.start_date</p>
                        <p>End date: @item.end_date</p>

                    }
                }


                <hr />

                <h5 class="card-title" font-weight: bold;">Education</h5>
                @foreach (var item in Model.EducationList)
                {
                    @item.university_name <span>, </span> @item.education_name <span>, </span> @item.study_years <span> years</span><br>
                }
                <hr>
                <h5 class="card-title" font-weight: bold;">Skills</h5>
                @foreach (var item in Model.SkillList)
                {
                    @item.name<br />
                }
                <hr>
                <h5 class="card-title" font-weight: bold;">Expertise</h5>
                @foreach (var item in Model.ExpertiseList)
                {
                    @item.name <span>
                        @for (int i = 0; i < Convert.ToInt32(item.rank_expertise_id); i++)
                        {
                            <span class="fa fa-star" style="color: orange;"></span>
                        }
                        <br />
                    </span><br />
                }
                <hr>
                <h5 class="card-title" font-weight: bold;">Main Abilities</h5>
                @foreach (var item in Model.MainAbilitiesList)
                {
                    @item.name; <br />
                }
                <hr>
                <h5 class="card-title" font-weight: bold;">Languages</h5>
                @foreach (var item in Model.FreelancerLanguageList)
                {
                    if (item.language_id == 1)
                    {

                        @item.name <br />
                    }
                }
         </div>
    </div>
</div>
       
@*<div>
        <h4>cv</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.birthday)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.birthday)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.nationality)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nationality)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.drivers_license)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.drivers_license)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.registration_date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.registration_date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.profil)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.profil)
            </dd>

        </dl>
    </div>*@



@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.cv_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

ProjektGruppF/ProjektGruppF/Views/freelancers/Create.cshtml
@model ProjektGruppF.Models.freelancer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>freelancer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phonenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phonenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phonenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.cv_id, "cv_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("cv_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.cv_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick="return confirm('Are you sure you want to save?')" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjektGruppF/ProjektGruppF/Views/freelancers/Delete.cshtml
@model ProjektGruppF.Models.freelancer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>freelancer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cv.nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cv.nationality)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjektGruppF/ProjektGruppF/Views/freelancers/Details.cshtml
@model ProjektGruppF.Models.freelancer

@{
    ViewBag.Title = "Freelancer profile";
}

<h2>Welcome @Model.firstname</h2>

<div>
    <h4>freelancer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cv.nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cv.nationality)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.freelancer_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjektGruppF/ProjektGruppF/Views/freelancers/Start.cshtml
@model ProjektGruppF.Models.freelancer

@{
    ViewBag.Title = "Freelancer profile";
}
<section id="First">


<h2 style="font-style:oblique">Welcome @Model.firstname</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd class="freeText">
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

       

    </dl>
    

    

</div>
</section>
<div id="second">
    <h3>Your personal Letter.</h3>
    <p>@Html.DisplayFor(model => model.PersonalLetter)</p>
    <br /><br /><br />
    <hr />
    <hr />
    <p style="color:blue">Wanna update you personal info? Click below.</p>
    <a href=@Url.Action("Edit", "freelancers") class="btn btn-primary" style="margin-top: 5%; margin-bottom: 5%; margin-left: 20%; margin-right: 35%; width: 50%;">Update profile</a>
    <br /><br />
    <p style="color:blue">Take a look at you CV here</p>
    <a href=@Url.Action("CV", "freelancers", new {  }) class="btn btn-primary" style="margin-top: 5%; margin-bottom: 5%; margin-left: 20%; margin-right: 35%; width: 50%;">View CV</a>
    <br /><br />
    <p style="color:blue">Edit your CV by clicking here</p>
    <a href=@Url.Action("Edit", "CVversion3", new {  }) class="btn btn-primary" style="margin-top: 5%; margin-bottom: 5%; margin-left: 20%; margin-right: 35%; width: 50%;">Edit CV</a>
</div>









@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.freelancer_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@