ProjektGruppF/ProjektGruppF/Controllers/CustomerLandingController.cs
using ProjektGruppF.Models;
using ProjektGruppF.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjektGruppF.Controllers
{
    public class CustomerLandingController : Controller
    {
        // GET: CustomerLanding


        public ActionResult Index()
        {
            FreelancerCardOperations flc = new FreelancerCardOperations();
            return View(flc.FreelancercardVMList());
        }
      
        public ActionResult FreelancerProfile(int freelancer_id, int cv_id)
        {
            FreelancerCardOperations flc = new FreelancerCardOperations();
            ViewBag.Message = freelancer_id.ToString();
            return View(flc.ViewFreelancer(freelancer_id, cv_id));
        }

        public ActionResult Testing(int cusID, int freeID)
        {
            FreelancerCardOperations flc = new FreelancerCardOperations();
            flc.SavefreeToCus(cusID, freeID);
            return RedirectToAction("Index");
        }
    }
}

ProjektGruppF/ProjektGruppF/Views/CustomerLanding/FreelancerProfile.cshtml
@model ProjektGruppF.ViewModels.Freelancer

@{
    ViewBag.Title = "FreelancerProfile";
}

<h2>@Model.Firstname @Model.Lastname</h2>
<div class="row">
    <div class="col-md-3">
        <div class="card border-secondary mb-3">
            <img src="https://icon-library.net/images/default-profile-icon/default-profile-icon-24.jpg" class="card-img-top" alt="An image of the freelancer" style="max-width:100%">
            <div class="card-body">
                <h5 class="card-title">@Model.Firstname @Model.Lastname</h5>
                <p class="card-text">
                    Age: @Model.Age <br>
                    Nationality: @Model.Nationality <br>
                    <hr />
                    Adress: @Model.Adress  <br>
                    Phonenumber: @Model.Phonenumber  <br>
                    Email: <a href="mailto:@Model.Email">@Model.Email</a>
                    Linkedin: <a href="https://se.linkedin.com/" target="_blank">https://se.linkedin.com/</a>
                    Github:<a href="https://github.com/" target="_blank">https://github.com/</a>
                </p>
                <div style="margin-top:3rem">
                    <input class="btn btn-primary" type="button" value="Print cv" onclick="myFunction()" />
                    <input class="btn btn-primary" type="button" value="Download cv" />
                    @using (Html.BeginForm("SaveFreeToCus", "savedFreelancers", new { cusID = 11, freeID = Model.Freelancer_id }))
                    {
                        <input class="btn btn-primary btn-lg btn-block" type="submit" value="Save" style="width: 40%; margin-top:1rem;" onclick="location.href='@Url.Action("SaveFreeToCus", "savedFreelancers")'" />
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="card border-secondary mb-3">
            <div class=" card-header">
                <h5 style="text-align:center">Curriculum Vitae</h5>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    @Model.Firstname @Model.Lastname 
                </h5>
                <p class="card-text">
                    @Model.CoverLetter <br>
                    Adress:@Model.Adress  <br>
                    Phonenumber: @Model.Phonenumber  <br>
                    Email: <a href="mailto:@Model.Email">@Model.Email</a> <br />
                    <hr />
                    Birthday:@Model.Birthday  <br>
                    Nationality: @Model.Nationality  <br>
                    <hr />
                    Drivers license: @Model.Drivers_license  <br>
                    <hr>
                    <h5 class="card-title" font-weight: bold;">Work experience</h5>
                    @foreach (var item in Model.Work_Experience_List)
                    {
                        <h6>@item.employer_name @item.start_date <span>-</span> @item.end_date </h6>
                        @item.job_title<br>
                        @item.role<br>
                    }
                    <hr>
                    <h5 class="card-title" font-weight: bold;">Education</h5>
                    @foreach (var item in Model.EducationList)
                    {
                        @item.university_name <span>, </span> @item.education_name <span>, </span> @item.study_years <span> years</span><br>
                    }
                    <hr>
                    <h5 class="card-title" font-weight: bold;">Skills</h5>
                    @foreach (var item in Model.SkillList)
                    {
                        @item.name<br />
                    }
                    <hr>

                    <h5 class="card-title" font-weight: bold;">Expertise</h5>
                 @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
                     Gör att glyphiconerna fungerar men då skriver den över all annan css*@
                    @foreach (var item in Model.ExpertiseList)
                    {
                    <div>
                        @item.name
                        <span>
                            @for (int i = 0; i < Convert.ToInt32(item.rank_expertise_id); i++)
                            {
                                <span class="fa fa-star" style="color: orange;"></span>
                            }
                        </span>
                    </div>
                    }

                    <hr>
                    <h5 class="card-title" font-weight: bold;">Main Abilities</h5>
                    @foreach (var item in Model.MainAbilitiesList)
                    {
                        @item.name <br />
                    }
                    <hr>
                    <h5 class="card-title" font-weight: bold;">Languages</h5>
                    @foreach (var item in Model.FreelancerLanguageList )
                    {
                        @item.name<br />
                    }
                </p>
            </div>
        </div>
    </div>
</div>
<script>
    function myFunction() {
        window.print();
    }
</script>

ProjektGruppF/ProjektGruppF/Views/CustomerLanding/Index.cshtml
@model List<ProjektGruppF.ViewModels.Freelancer>
@{
    ViewBag.Title = "Index";
}

<h2 style="text-align: center; margin-top: 3%;">Available Freelancers</h2>


@Html.AntiForgeryToken()

<input id="filter" type="text" placeholder="Search for skill, expertise or freelancer" style="width: 50%; height: 50px; margin-top: 2%; margin-bottom: 3%; margin-left: 37%;" />
<div id="results">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-3 colsm-3 col-xs-6 results" style="display:flex;">
                <div class="card bg-light mb-3 " style="margin-bottom:20px;">
                    <img src="https://icon-library.net/images/default-profile-icon/default-profile-icon-24.jpg" class="card-img-top" alt="A picture of the freelancer" style="height:180px; width:100%; ">
                    <div class="card-body">
                        <h5 class="card-title">@item.Firstname @item.Lastname</h5>
                        <p class="card-text" style=" flex:1;">
                            Age: @item.Age <br>
                            Nationality: @item.Nationality  <br>
                            @foreach (var skill in item.SkillList)
                            {
                                @skill.name<br />
                            }
                            @foreach (var expertise in item.ExpertiseList)
                            {
                                @expertise.name
                                <span>
                                    @for (int i = 0; i < Convert.ToInt32(expertise.rank_expertise_id); i++)
                                    {
                                        <span class="fa fa-star" style="color: orange;"></span>
                                    }
                                    <br />
                                </span>
                            }
                        </p>
                        @using (Html.BeginForm("FreelancerProfile", "CustomerLanding", new { freelancer_id = item.Freelancer_id, cv_id = item.Cv_id }))
                        {
                            <input class="btn btn-primary" type="submit" value="View CV" style="width: 40%; float: left;" onclick="location.href='@Url.Action("FreelancerProfile", "CustomerLanding")'" />
                        }

                        @***************** Knapp för att spara frilansare****************@
                        @using (Html.BeginForm("Testing", "CustomerLanding", new { cusID = 11, freeID = item.Freelancer_id }))
                        {
                            <input class="btn btn-primary" type="submit" value="Save" style="width: 40%; float: right;" onclick="location.href='@Url.Action("Testing", "savedFreelancers")'" />
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section scripts {
    <script>
       @* $(document).ready(function filter() {
            $('#input').on('keyup', function () {
                var value = $(this).val().toLowerCase();
                $('.searchField *').filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });*@
  @*  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>*@
        $(document).ready(function filter() {
            $("#filter").keyup(function () {

                // Retrieve the input field text and reset the count to zero
                var filter = $(this).val(),
                    count = 0;

                // Loop through the comment list
                $('#results div').each(function () {


                    // If the list item does not contain the text phrase fade it out
                    if ($(this).text().search(new RegExp(filter, "i")) < 0) {
                        $(this).hide();  // MY CHANGE

                        // Show the list item if the phrase matches and increase the count by 1
                    } else {
                        $(this).show(); // MY CHANGE
                        count++;
                    }

                });

            });
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

}